---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
