---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/ingress-nginx/overlays/test
